### ISSUE TITLE
Make Machine Gun tower look different from Cannon tower

### ISSUE THREAD

**Issue by danielmoniz** [danielmoniz/tower-defense#32]
The Machine Gun and Cannon towers currently look identical. Do something simple to make them look different, eg. make the barrel of the Machine Gun look like a gatling gun (multi-barrelled).

These changes would happen in the MachineGunRenderer.js file (src/js/renderers/towers/). One needs to be made if it does not exist. FlamethrowerRenderer can be used as a template.

**Comment by itsamiga** [comment]
Addressed in branch gun-renderers and pushed (not yet merged)

- added methods to TowerRenderer.js to be inherited by subclasses
- added MachineGunRenderer.js, uses methods mentioned above
- updated FlamethrowerRenderer.js (likewise)
(- Cannon type towers still use default)
