### ISSUE TITLE
Add an info panel

### ISSUE THREAD

**Issue by danielmoniz** [danielmoniz/tower-defense#39]
The panel should show info about the currently selected tower or enemy. We can also show information about a tower that is about to be placed.

The panel should show:

For enemies:
Name/type
Speed
Current hit points (against max Hit points)
Value (credits for killing)
Size (width/height)

For towers:
Name/type
Price
Damage (per shot)
Range
Damage per second (DPS)
Clip size
Firing time (time between shots)
Reload time (time between clips)
Profit multiplier (only if not 1)

XP (and/or rank if it exists) (placed towers only)
Kills (placed towers only)
Total damage (placed towers only)
Size (width/height)

**Comment by itsamiga** [comment]
XP/Kills to be handled in resolving next issues (recording tower kills, experience, levels)
