### ISSUE TITLE
Towers should gain experience/levels when shooting/killing enemies

### ISSUE THREAD

**Issue by danielmoniz** [danielmoniz/tower-defense#41]
Towers should have an observable attribute called `experience`.

They should automatically get XP when killing enemies. Their level should be calculable from their experience.

Initially, all enemies can provide the same amount of XP, but eventually, more powerful enemies should provide more XP.

**Comment by itsamiga** [comment]
Towers gain XP from kills
- Still need to add XP on firing, adjusted for a tower's rate of fire

**Comment by danielmoniz** [comment]
Edited this and moved the second half (gaining XP when firing) to issue #56.
