### ISSUE TITLE
Towers should have stats based on XP/level

### ISSUE THREAD

**Issue by danielmoniz** [danielmoniz/tower-defense#42]
Towers should improve based on their current level. This should be a simple formula. The tower's level should be calculable from their experience level via a simple formula. Their attack power, range, and so on should improve (exponentially, but slow exponentially) each level. They could improve at different rates, but for now the same rate is acceptable.

Levels should be exponential. For example, each level could require 15% more experience than the last.

The formula for increased damage (for example) could be as simple as:

```
total_attack_power = current_attack_power * (1.01 ^ current_level)
```
This example would allow for a 1% increase (compounded) in attack power per level.

Because their updated stats should be calculable, these should probably be `@computed` methods using MobX.

**Comment by itsamiga** [comment]
Attack power and range are now updated based on level
- Range increases are not reflected in range indicator upon selecting improved tower

**Comment by danielmoniz** [comment]
Range increases are now reflected in range circles.
